
#define ca_cert "-----BEGIN CERTIFICATE-----\n\
MIIEVzCCAj+gAwIBAgIRALBXPpFzlydw27SHyzpFKzgwDQYJKoZIhvcNAQELBQAw\n\
TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh\n\
cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMjQwMzEzMDAwMDAw\n\
WhcNMjcwMzEyMjM1OTU5WjAyMQswCQYDVQQGEwJVUzEWMBQGA1UEChMNTGV0J3Mg\n\
RW5jcnlwdDELMAkGA1UEAxMCRTYwdjAQBgcqhkjOPQIBBgUrgQQAIgNiAATZ8Z5G\n\
h/ghcWCoJuuj+rnq2h25EqfUJtlRFLFhfHWWvyILOR/VvtEKRqotPEoJhC6+QJVV\n\
6RlAN2Z17TJOdwRJ+HB7wxjnzvdxEP6sdNgA1O1tHHMWMxCcOrLqbGL0vbijgfgw\n\
gfUwDgYDVR0PAQH/BAQDAgGGMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEFBQcD\n\
ATASBgNVHRMBAf8ECDAGAQH/AgEAMB0GA1UdDgQWBBSTJ0aYA6lRaI6Y1sRCSNsj\n\
v1iU0jAfBgNVHSMEGDAWgBR5tFnme7bl5AFzgAiIyBpY9umbbjAyBggrBgEFBQcB\n\
AQQmMCQwIgYIKwYBBQUHMAKGFmh0dHA6Ly94MS5pLmxlbmNyLm9yZy8wEwYDVR0g\n\
BAwwCjAIBgZngQwBAgEwJwYDVR0fBCAwHjAcoBqgGIYWaHR0cDovL3gxLmMubGVu\n\
Y3Iub3JnLzANBgkqhkiG9w0BAQsFAAOCAgEAfYt7SiA1sgWGCIpunk46r4AExIRc\n\
MxkKgUhNlrrv1B21hOaXN/5miE+LOTbrcmU/M9yvC6MVY730GNFoL8IhJ8j8vrOL\n\
pMY22OP6baS1k9YMrtDTlwJHoGby04ThTUeBDksS9RiuHvicZqBedQdIF65pZuhp\n\
eDcGBcLiYasQr/EO5gxxtLyTmgsHSOVSBcFOn9lgv7LECPq9i7mfH3mpxgrRKSxH\n\
pOoZ0KXMcB+hHuvlklHntvcI0mMMQ0mhYj6qtMFStkF1RpCG3IPdIwpVCQqu8GV7\n\
s8ubknRzs+3C/Bm19RFOoiPpDkwvyNfvmQ14XkyqqKK5oZ8zhD32kFRQkxa8uZSu\n\
h4aTImFxknu39waBxIRXE4jKxlAmQc4QjFZoq1KmQqQg0J/1JF8RlFvJas1VcjLv\n\
YlvUB2t6npO6oQjB3l+PNf0DpQH7iUx3Wz5AjQCi6L25FjyE06q6BZ/QlmtYdl/8\n\
ZYao4SRqPEs/6cAiF+Qf5zg2UkaWtDphl1LKMuTNLotvsX99HP69V2faNyegodQ0\n\
LyTApr/vT01YPE46vNsDLgK+4cL6TrzC/a4WcmF5SRJ938zrv/duJHLXQIku5v0+\n\
EwOy59Hdm0PT/Er/84dDV0CSjdR/2XuZM3kpysSKLgD1cKiDA+IRguODCxfO9cyY\n\
Ig46v9mFmBvyH04=\n\
-----END CERTIFICATE-----\n"

// #define ca_cert "-----BEGIN CERTIFICATE-----\n\
// MIIDyTCCA2+gAwIBAgIUD2bkx3kAhW2K4kFHN67TuU/uOsgwCgYIKoZIzj0EAwIw\n\
// gbwxCzAJBgNVBAYTAklOMRMwEQYDVQQIDApUYW1pbCBOYWR1MRAwDgYDVQQHDAdD\n\
// aGVubmFpMTkwNwYDVQQKDDBTb2NpZXR5IGZvciBFbGVjdHJvbmljIFRyYW5zYWN0\n\
// aW9ucyBhbmQgU2VjdXJpdHkxMDAuBgNVBAsMJ0NyeXB0b2xvZ3kgYW5kIENvbXB1\n\
// dGluZyBSZXNlYXJjaCBHcm91cDEZMBcGA1UEAwwQZWFiaGVkeWEgcm9vdCBjYTAe\n\
// Fw0yNDA5MjQwNjQzMjBaFw00NDA5MTkwNjQzMjBaMIG8MQswCQYDVQQGEwJJTjET\n\
// MBEGA1UECAwKVGFtaWwgTmFkdTEQMA4GA1UEBwwHQ2hlbm5haTE5MDcGA1UECgww\n\
// U29jaWV0eSBmb3IgRWxlY3Ryb25pYyBUcmFuc2FjdGlvbnMgYW5kIFNlY3VyaXR5\n\
// MTAwLgYDVQQLDCdDcnlwdG9sb2d5IGFuZCBDb21wdXRpbmcgUmVzZWFyY2ggR3Jv\n\
// dXAxGTAXBgNVBAMMEGVhYmhlZHlhIHJvb3QgY2EwWTATBgcqhkjOPQIBBggqhkjO\n\
// PQMBBwNCAATpqZEVGfsGsV8u2nXCVumjL7zlLDKAGzs3t5EdLzLJa1liOlKWBqfV\n\
// Y6f4oL9w7E3nlk+q1eazCmymrEy+4shCo4IBSzCCAUcwHQYDVR0OBBYEFJWQpK5G\n\
// dmyJ7fPUcxlfP8qiy1d2MA8GA1UdEwEB/wQFMAMBAf8wCwYDVR0PBAQDAgH2MIH8\n\
// BgNVHSMEgfQwgfGAFJWQpK5GdmyJ7fPUcxlfP8qiy1d2oYHCpIG/MIG8MQswCQYD\n\
// VQQGEwJJTjETMBEGA1UECAwKVGFtaWwgTmFkdTEQMA4GA1UEBwwHQ2hlbm5haTE5\n\
// MDcGA1UECgwwU29jaWV0eSBmb3IgRWxlY3Ryb25pYyBUcmFuc2FjdGlvbnMgYW5k\n\
// IFNlY3VyaXR5MTAwLgYDVQQLDCdDcnlwdG9sb2d5IGFuZCBDb21wdXRpbmcgUmVz\n\
// ZWFyY2ggR3JvdXAxGTAXBgNVBAMMEGVhYmhlZHlhIHJvb3QgY2GCFA9m5Md5AIVt\n\
// iuJBRzeu07lP7jrIMAkGA1UdEQQCMAAwCgYIKoZIzj0EAwIDSAAwRQIhALduP3WP\n\
// VR62CnZ/AfyHCwLlNbCnnOvnjuGojUz73S6HAiAt0bsARAm/gQqHZj22J+9OkdOD\n\
// aN0J5IW5K3yakFsRtw==\n\
// -----END CERTIFICATE-----\n"

// #define ca_cert "-----BEGIN CERTIFICATE-----\n\
// MIIDyDCCA2+gAwIBAgIUHl84sbw+I3lpMGLmzmb5AzNj4ccwCgYIKoZIzj0EAwQw\n\
// gbwxCzAJBgNVBAYTAklOMRMwEQYDVQQIDApUYW1pbCBOYWR1MRAwDgYDVQQHDAdD\n\
// aGVubmFpMTkwNwYDVQQKDDBTb2NpZXR5IGZvciBFbGVjdHJvbmljIFRyYW5zYWN0\n\
// aW9ucyBhbmQgU2VjdXJpdHkxMDAuBgNVBAsMJ0NyeXB0b2xvZ3kgYW5kIENvbXB1\n\
// dGluZyBSZXNlYXJjaCBHcm91cDEZMBcGA1UEAwwQZWFiaGVkeWEgY2Egcm9vdDAe\n\
// Fw0yNDA1MjUxMzUzMzFaFw00NDA1MjAxMzUzMzFaMIG8MQswCQYDVQQGEwJJTjET\n\
// MBEGA1UECAwKVGFtaWwgTmFkdTEQMA4GA1UEBwwHQ2hlbm5haTE5MDcGA1UECgww\n\
// U29jaWV0eSBmb3IgRWxlY3Ryb25pYyBUcmFuc2FjdGlvbnMgYW5kIFNlY3VyaXR5\n\
// MTAwLgYDVQQLDCdDcnlwdG9sb2d5IGFuZCBDb21wdXRpbmcgUmVzZWFyY2ggR3Jv\n\
// dXAxGTAXBgNVBAMMEGVhYmhlZHlhIGNhIHJvb3QwWTATBgcqhkjOPQIBBggqhkjO\n\
// PQMBBwNCAASJ6D9YSwtHViisCFsna5K7On0QOJJ6DQ8qW5RF8Qb5dZ2kZG5wYWAv\n\
// TUgyqF5xKsk7B5KmkCqaWGgnk8Hxmmg/o4IBSzCCAUcwHQYDVR0OBBYEFLPGlVhN\n\
// 3VkPDpj/guac4umXxZaqMA8GA1UdEwEB/wQFMAMBAf8wCwYDVR0PBAQDAgH2MIH8\n\
// BgNVHSMEgfQwgfGAFLPGlVhN3VkPDpj/guac4umXxZaqoYHCpIG/MIG8MQswCQYD\n\
// VQQGEwJJTjETMBEGA1UECAwKVGFtaWwgTmFkdTEQMA4GA1UEBwwHQ2hlbm5haTE5\n\
// MDcGA1UECgwwU29jaWV0eSBmb3IgRWxlY3Ryb25pYyBUcmFuc2FjdGlvbnMgYW5k\n\
// IFNlY3VyaXR5MTAwLgYDVQQLDCdDcnlwdG9sb2d5IGFuZCBDb21wdXRpbmcgUmVz\n\
// ZWFyY2ggR3JvdXAxGTAXBgNVBAMMEGVhYmhlZHlhIGNhIHJvb3SCFB5fOLG8PiN5\n\
// aTBi5s5m+QMzY+HHMAkGA1UdEQQCMAAwCgYIKoZIzj0EAwQDRwAwRAIgWisIQXtJ\n\
// SuFy3BkDOXuDUxAKxeVZ+UJ+Itov8VETKzUCIBTNr3fi+VkVSExbvj4eRUukZaSb\n\
// yVtYVNU4psgaGbLX\n\
// -----END CERTIFICATE-----\n"



